# Generated by Django 5.2.14 on 2026-05-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labdata', '0002_derived_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('date', 'Date'), ('boolean', 'Boolean'), ('textarea', 'Long text'), ('derived', 'Derived / calculated')], default='text', max_length=20),
        ),
    ]
