# Generated by Django 5.2.14 on 2026-06-02 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labdata', '0005_plot_configs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observationrow',
            options={'ordering': ['table__order', 'serial_number', 'id']},
        ),
        migrations.RenameField(
            model_name='plotconfig',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='plotconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='plotconfig',
            name='description',
        ),
        migrations.RemoveField(
            model_name='plotconfig',
            name='x_label',
        ),
        migrations.RemoveField(
            model_name='plotconfig',
            name='y_label',
        ),
        migrations.AddField(
            model_name='plotconfig',
            name='x_axis_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='plotconfig',
            name='y_axis_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='calculation_formula',
            field=models.CharField(blank=True, help_text='Only for derived fields. Row-wise examples: length/time, 2*pi*r, sin(theta*pi/180).', max_length=500),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='experiment',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='labdata.experiment'),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='chart_type',
            field=models.CharField(choices=[('scatter', 'Scatter plot'), ('line', 'Line plot'), ('bar', 'Bar chart')], default='scatter', max_length=20),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='x_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x_plot_configs', to='labdata.datafield'),
        ),
        migrations.AlterField(
            model_name='plotconfig',
            name='y_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='y_plot_configs', to='labdata.datafield'),
        ),
    ]
