# Generated by Django 5.2.15 on 2026-06-15 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labdata', '0007_plot_fit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafield',
            name='calculation_formula',
            field=models.CharField(blank=True, help_text='Only for derived fields. Examples: length/time, 2*pi*r, sin(theta*pi/180).', max_length=500),
        ),
    ]
